[package]
name = "usdt"
version = "0.1.0"
authors = ["Benjamin Naecker <bnaecker@fastmail.com>"]
edition = "2018"

[dependencies]
quote = "1.0.9"
syn = { version = "1.0.60", features = ["full"] }
pest = "2.1.3"
pest_derive = "2.1.0"

[lib]
proc-macro = true
