[package]
name = "usdt"
version = "0.1.8"
authors = ["Benjamin Naecker <bnaecker@fastmail.com>"]
edition = "2018"

[dependencies]
usdt-macro = { path = "./usdt-macro", version = "0.1.4" }
dtrace-parser = { path = "./dtrace-parser", version = "0.1.7" }
dof = { path = "./dof", version = "0.1.2" }
cc = "1.0"
structopt = "0.3.21"

[workspace]
members = ["probe-test"]
default-members = ["dtrace-parser", "dof", "usdt-macro"]

[features]
asm = ["dtrace-parser/asm"]
