[workspace]
members = [
	"dof",
	"dtrace-parser",
	"probe-test-build",
	"probe-test-macro",
	"usdt",
	"usdt-impl",
	"usdt-macro"
]
default-members = [
	"dtrace-parser",
	"usdt",
	"usdt-impl",
	"usdt-macro"
]
