[workspace]
members = ["dof", "dtrace-parser", "usdt", "usdt-impl", "usdt-macro", "probe-test-macro", "probe-test-build"]
default-members = ["dof", "dtrace-parser", "usdt", "usdt-impl", "usdt-macro"]
