[package]
name = "usdt-impl"
version = "0.1.3"
authors = ["Benjamin Naecker <ben@oxidecomputer.com>"]
edition = "2018"

[dependencies]
proc-macro2 = "1.0.24"
quote = "1.0.9"
dtrace-parser = { path = "../dtrace-parser", version = "0.1.8" }

dof = { path = "../dof", version = "0.1.2", optional = true }
libc = { version = "0.2.88", optional = true }
syn = { version = "1.0.60", optional = true}
byteorder = { version = "1.4.2", optional = true }

[features]
asm = ["dof", "libc", "syn", "byteorder"]
