[package]
name = "usdt-macro"
version = "0.1.4"
authors = ["Benjamin Naecker <bnaecker@fastmail.com>"]
edition = "2018"

[dependencies]
syn = { version = "1.0.60", features = ["full"] }
proc-macro2 = "1.0.24"
dtrace-parser = { path = "../dtrace-parser", version = "0.1.5" }

[lib]
proc-macro = true
