[package]
name = "usdt-macro"
version = "0.1.1"
authors = ["Benjamin Naecker <bnaecker@fastmail.com>"]
edition = "2018"

[dependencies]
quote = "1.0.9"
syn = { version = "1.0.60", features = ["full"] }
proc-macro2 = "1.0.24"
dtrace-parser = { path = "../dtrace-parser" }
pest = "2.1.3"

[lib]
proc-macro = true
