[package]
name = "probe-test"
version = "0.1.0"
authors = ["Benjamin Naecker <bnaecker@fastmail.com>"]
edition = "2018"

[dependencies]
usdt = { path = "../" }

[build-dependencies]
usdt = { path = "../" }
cc = "1.0"

[features]
asm = ["usdt/asm"]
