[package]
name = "dtrace-parser"
version = "0.1.6"
authors = ["Benjamin Naecker <bnaecker@fastmail.com>"]
edition = "2018"

[dependencies]
pest = "2.1.3"
pest_derive = "2.1.0"
thiserror = "1.0.24"
textwrap = "0.13.4"
cc = "1.0"

[dev-dependencies]
rstest = "0.6.4"
expectorate = "1.0.2"
