[package]
name = "dtrace-parser"
version = "0.1.2"
authors = ["Benjamin Naecker <bnaecker@fastmail.com>"]
edition = "2018"

[dependencies]
pest = "2.1.3"
pest_derive = "2.1.0"
thiserror = "1.0.24"

[dev-dependencies]
rstest = "0.6.4"
