[package]
name = "usdt"
version = "0.1.9"
authors = ["Benjamin Naecker <ben@oxidecomputer.com>"]
edition = "2018"

[dependencies]
thiserror = "1.0.24"
proc-macro2 = "1.0.24"
usdt-impl = { path = "../usdt-impl", version = "0.1.2" }
usdt-macro = { path = "../usdt-macro", version = "0.1.5" }
dtrace-parser = { path = "../dtrace-parser", version = "0.1.8" }
dof = { path = "../dof", version = "0.1.2" }

[features]
default = ["asm"]
asm = ["usdt-impl/asm"]
