[package]
name = "usdt"
version = "0.1.2"
authors = ["Benjamin Naecker <bnaecker@fastmail.com>"]
edition = "2018"

[[bin]]
name = "dusty"
path = "src/main.rs"

[dependencies]
structopt = "0.3.21"
quote = "1.0.9"
usdt-macro = { path = "../usdt-macro", version = "0.1.3" }
dtrace-parser = { path = "../dtrace-parser", version = "0.1.2" }
