[package]
name = "probe-test-build"
version = "0.1.0"
authors = ["Benjamin Naecker <bnaecker@fastmail.com>"]
edition = "2018"

[dependencies]
usdt = { path = "../usdt" }

[build-dependencies]
usdt = { path = "../usdt" }

[features]
asm = ["usdt/asm"]
