[package]
name = "dof"
version = "0.1.4"
authors = ["Benjamin Naecker <ben@oxidecomputer.com>",
           "Adam H. Leventhal <ahl@oxidecomputer.com>"]
edition = "2018"
license = "Apache-2.0"
description = "Tools to read and write the DTrace Object Format (DOF)"
repository = "https://github.com/oxidecomputer/usdt.git"

[dependencies]
goblin = "0.3.4"
pretty-hex = "0.2.1"
structopt = "0.3.21"
thiserror = "1.0.24"
zerocopy = "0.3.0"
