[package]
name = "dof"
version = "0.1.2"
authors = ["Benjamin Naecker <ben@oxidecomputer.com>"]
edition = "2018"

[dependencies]
zerocopy = "0.3.0"
structopt = "0.3.21"
goblin = "0.3.4"
thiserror = "1.0.24"
pretty-hex = "0.2.1"

[build-dependencies]
bindgen = "0.57.0"
